#
#    This file is part of SSL.
#
#    Copyright 2018 Boussicault Adrien (adrien.boussicault@u-bordeaux.fr)
#
#    SSL is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    SSL is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with SSL.  If not, see <http://www.gnu.org/licenses/>.
#

#+TITLE: Calcul de la commande en vitesse linéraire et angulaire d'un robot holonome

# To generate the html documentation with mathemtics formula, execute the following command :
# emacs FILE.org -batch -f org-html-export-to-html --kill

#+OPTIONS: tex:dvipng

L'objectif de ce document est de déterminer la commande en vitesse d'un 
robot holonome en fonction d'une consigne en vitesse.

Les robots holonomes sont dirigés en donnant, tout les $\Delta t$ temps, une 
consigne en vitesse linéaire et angulaire constante exprimée dans le
repère fixe qui coincide, au moment du calcul, avec le repère mobile du robot.

L'objectif de ce document est de détermriner ces vitesses de sorte à ce que le
robot suive une vitesse linéaire et angulaire exprimée dans le repère
absolue.

* Définitions et notations 

Soit $t$ la variable du temps.

Soit $\mathcal{O} = (0, \overrightarrow{i}, \overrightarrow{j})$, le repère 
absolu.

Soit $M(t)$ la position du robot holonome.
Soit $\theta(t)$ la position angulaire du robot holonome dans le repère absolue.

On notera par $V(t)$ et $\omega(t)$ la vitesse linéaire et angulaire exprimée dans le repère absolue :
 - Vitesse linéaire absolu : $V(t) = \left. \frac{\partial OM}{\partial t} \right|_{\mathcal{O}}$.
 - Vitesse angulaire absolu : $\omega = \dot{\theta}$.

On suppose qu'au temps $t=T$, l'application est dans l'attente d'une nouvelle 
commande en vitesse linéaire et angulaire.

La commande du robot, à l'instant $t=T$, se fait en comunicant au robot, une 
vitesse linéaire $V_C$ et angulaire $\omega_C$ absolue exprimée 
dans le repère du robot. Cette commande restera constante entre $t=T$ et $t=T+\Delta t$.

Soit $\mathcal{R}(t) = (M(t), \overrightarrow{i_1}(t), \overrightarrow{j_1}(t))$, le repère relatif au robot au temps $t$.

Soit $V_r(t)$ le vecteur de vitesse absolue du robot exrpimée dans le repère $R(t)$.
Ce vecteur est différent du vecteur vitesse relatif au robot exprimé dans le repère du robot. En effet, ce vecteur qui vaut $\left. \frac{\partial M(t)M(t)}{\partial t} \right|_{\mathcal{R}}$ est nul.

Le vecteur $V_r(t)$ est, quant à lui, définit par :

$$
V_r(t) = \left. \frac{\partial M(t=T)M(t)}{\partial t} \right|_{\mathcal{R}} = \left. \frac{\partial OM(t)}{\partial t} \right|_{\mathcal{R}}.
$$

Il faut donc bien distinguer la différence entre le vecteur de vitesse relatif 
au repère du robot et le vecteur de vitesse absolue exprimée dans le repère du 
robot.

Lorsque $t \in [T, T+\Delta t]$, on sait que $V_r(t) = V_C$ et $\omega(t)=\omega_C$. 
On sait que l'utilisateur souhaite que le robot se déplace à une position 
linéaire $M_{consigne}(t)$ et angulaire $\theta_{consgine}(t)$ donné en 
commandant le robot à l'aide de $V_C$ et $\omega_C$.
Pour cela, l'utilisateur dispose de la vitesse linéaire et angulaire 
$V_{consigne}$, $\omega_{consigne}$ exprimée dans le repère absolu, définit par :
$V_{consigne} = \left. \frac{\partial OM_{consigne}}{\partial t} \right|_{\mathcal{O}}$
et par
$\omega_{consigne} = \partial_t( \theta_{consigne} )$.

Comme la commande entre $t=T$ et $t=T+\Delta t$ est constante, il n'est pas possible
de faire en sorte que $M(t) = M_{consigne}(t)$ et $\theta(t) = \theta_{consigne}(t)$, cependant, on peut 
calculer $V_C$ et $\omega_C$ de sorte à ce que 
$M(T) = M_{consigne}(T)$, $\theta(T) = \theta_{consigne}(T)$, 
$M(T+\Delta t) = M_{consigne}(T+\Delta t)$ et $\theta(T+\Delta t) = \theta_{consigne}(T+\Delta t)$. 

Écrit autrement, on a les rélations :

$$
\int_{t=T}^{T+\Delta t} V_{consigne} = \int_{t=T}^{T+\Delta t} V(t) dt
$$

et

$$
\int_{t=T}^{t+\Delta t} \omega_{consigne}(t) dt = \int_{t=T}^{T+\Delta t} \omega(t) dt
$$


Ce calcul est l'objet de ce document.

* Détail du calcul


La vitesse absolu du robot peut être exprimée dans le repère absolu 
$\mathcal{O}$ ou dans le repère $\mathcal{R}$ du robot. On passe 
d'une vitesse à l'autre par la relation suivante : 

$$
\left. 
    \frac{\partial OM}{\partial t}
\right|_{\mathcal{O}}
= 
M_{\mathcal{R} \rightarrow \mathcal{O}}
\cdot
\left. 
    \frac{\partial OM}{\partial t}
\right|_{\mathcal{R}}
$$

où $M_{\mathcal{R} \rightarrow \mathcal{O}}$ est la matrice du changement de
repère de $\mathcal{R}$ dans $\mathcal{O}$.

Ainsi, 

$$
V(t)
=
\left( \begin{array}{cc}
\cos{\theta} & -\sin{\theta} \\
\sin{\theta} & \cos{\theta}
\end{array} \right)
\cdot
V_r(t)
$$

et donc

$$
V_r(t)
=
\left( \begin{array}{cc}
\cos{\theta} & \sin{\theta} \\
-\sin{\theta} & \cos{\theta}
\end{array} \right)
\cdot
V(t).
$$

Dans la commande du robot, on peut modifier les valeurs de $V$ et
$\omega$ toutes les $\Delta t$ secondes. Il s'agit de la commande.
La valeur de $V$ est la vitesse absolu que l'on souhaite imprimer au robot.

Il n'est donc pas possible de faire en sorte que $V_C$ soit égale à la vitesse consigne $V_{Consigne}$.

Cependant, on a vu précédement que l'on peut faire en sorte d'avoir :

$$
\int_{t=T}^{T+\Delta t} V_{consigne} = \int_{t=T}^{T+\Delta t} V(t) dt
$$

et

$$
\int_{t=T}^{t+\Delta t} \omega_{consigne}(t) dt = \int_{t=T}^{T+\Delta t} \omega(t) dt
$$

Or on sait que $\omega(t) = \omega_C$ si $t \in [T, T+\Delta t]$, ainsi on a,
 
$$
\omega_C = \frac{1}{\Delta t} \int_{t=T}^{T+\Delta t} \omega_{consigne}(t) dt.
$$


Faisons le changement de repère entre $V(t)$ et $V_r(t)$ :
$$
\int_{t=T}^{T+\Delta t} V(t) dt 
=
\int_{t=T}^{T+\Delta t}
\left( \begin{array}{cc}
\cos{\theta(t)} & -\sin{\theta(t)} \\
\sin{\theta(t)} & \cos{\theta(t)}
\end{array} \right) \cdot V_r(t) \ dt
$$

Comme la valeur de $V_r$ est constant entre $T$ et $T+ \Delta t$ et vaut $V_C$,
on a 

$$
\int_{t=T}^{T+ \Delta t} V(t) dt
=
\int_{t=T}^{T+ \Delta t}
\left( \begin{array}{cc}
\cos{\theta(t)} & -\sin{\theta(t)} \\
\sin{\theta(t)} & \cos{\theta(t)}
\end{array} \right) dt
\cdot V_C
$$

et donc

$$
V_C
=
\left(
\int_{t=T}^{T+\Delta t}
\left( \begin{array}{cc}
\cos{\theta(t)} & -\sin{\theta(t)} \\
\sin{\theta(t)} & \cos{\theta(t)}
\end{array} \right) dt
\right)^{-1} \cdot \int_{t=T}^{T+\Delta t} V(t) dt 
$$

Dans la commande du robot, la commande angulaire est constante
et identique à la vitesse angulaire du robot et est consatant entre $T$ et 
$T+\Delta t$. On a donc :
$\partial \cos{\theta} = - \omega_C \sin{\theta}$
et
$\partial \sin{\theta} = \omega_C \cos{\theta}$.

Ainsi,
 
$$
V_C
=
\omega_C
\cdot
\left(
\left[
\left( \begin{array}{cc}
\sin{\theta(t)} & \cos{\theta(t)} \\
-\cos{\theta(t)} & \sin{\theta(t)}
\end{array}
\right) 
\right]_{T}^{T+\Delta t}
\right)^{-1}
\cdot 
\int_{t=T}^{T+\Delta t} V(t) dt 
$$

avec $\theta(u) = \omega_C \cdot (u-t) + \theta(t)$.

Il suffit maintenant de remplacer 
$\int_{t=T}^{T+\Delta t} V(t) dt$
par la consigne 
$\int_{t=T}^{T+\Delta t} V_{consigne}(t) dt$ :

$$
V_C
=
\omega_C
\cdot
\left(
\left[
\left( \begin{array}{cc}
\sin{\theta(t)} & \cos{\theta(t)} \\
-\cos{\theta(t)} & \sin{\theta(t)}
\end{array}
\right) 
\right]_{t=T}^{T+\Delta t}
\right)^{-1}
\cdot 
\int_{t=T}^{T+\Delta t} V_{consigne}(t) dt 
$$


* Résumé :

Pour résumé, les valeurs de commande $V_C$ et $\omega_C$ s'obtiennet à partir
de la valeur de consigne $V_{consigne}$ et $\omega_{consigne}$ de la 
façon suivante :

Pour toute valeure $u$ de $[T, T+\Delta t[$, on a :

$$
\omega_C
=
\frac{1}{\Delta t} \int_{t=T}^{T+\Delta t} \omega_{consigne}(t) dt.
=
\frac{
\theta_{consigne}(T+\Delta t) - \theta_{consigne}(T)
}{
\Delta t
}
\approx
\omega_{consigne}(T)
$$

et 

$$
V_C(u)
=
\omega_C
\cdot
\left(
\left[
\left( \begin{array}{cc}
\sin{\theta(T)} & \cos{\theta(T)} \\
-\cos{\theta(T)} & \sin{\theta(T)}
\end{array}
\right) 
\right]_{t=T}^{T+\Delta t}
\right)^{-1}
\cdot 
\int_{t=T}^{T+\Delta t} V_{consigne}(t) dt 
$$

avec 

$$
\int_{t=T}^{T+\Delta t} V_{consigne}(t) dt 
=
\left(
OM_{consigne}( T+\Delta t) - OM_{consigne}(T)
\right)
\approx
V_{consigne}(t) * dt
$$

et enfin 

$$
\theta(u) = \omega_C * (u-T) + \theta(T).
$$

