#+TITLE: Give tangent calculus for some objects

# To generate the html documentation with mathemtics formula, execute the following command :
# emacs FILE.org -batch -f org-html-export-to-html --kill
#
# You need to install org-mode.

#+OPTIONS: tex:dvipng


* Tangents of Cirles

** Tangent of two circles 

Let $A$ and $B$ be two centers of two circles $\mathcal{C}_A$ and 
$\mathcal{C}_B$ such that $\mathcal{C}_A$ do not overlap $\mathcal{C}_B$.

Let $r_A$ and $r_B$ be the two radius of $\mathcal{C}_A$ and $\mathcal{C}_B$.

Let $M \in \mathcal{C}_A$ and $N \in \mathcal{C}_B$ be two points such that 
the line $(MN)$ is tangent to the circles $\mathcal{C}_A$ and $\mathcal{C}_B$.

As the line $(MN)$ is tangent to $\mathcal{C}_A$ and $\mathcal{C}_B$, then 
$\overrightarrow{AM}$ and $\overrightarrow{BN}$ are colinear.

Let $\overrightarrow{u}$ be the orthonormal vector of $\overrightarrow{MN}$ such that 

$$
M  = A + r_A \cdot \overrightarrow{u}
\text{ and }
N  = B + \epsilon_1 \cdot r_B \overrightarrow{u}
$$

where

$$
\epsilon_1 = \left\{\begin{array}{ll}
    -1 & \text{if $\overrightarrow{AM}$ and $\overrightarrow{BN}$ are opposite,} \\
    +1 & \text{otherwise}.
    \end{array}
\right.
$$.

We obtain that 

$$
\overrightarrow{MN} = B - A + (\epsilon_1 \cdot r_B - r_A) \cdot \overrightarrow{u}.
$$

We know that $\overrightarrow{MN}$ is orthogonal to $\overrightarrow{u}$, so 
that means $< \overrightarrow{MN} | \overrightarrow{u} > = 0$. 

By definition, $\overrightarrow{u}$ is normal, so we obtain :

$$
\left\{ \begin{array}{l}
<B-A | \overrightarrow{u}> + (\epsilon_1 \cdot r_B - r_A) = 0, \\
\|\overrightarrow{u}\| = 1.
\end{array}
\right.
$$

Let $\theta$ be the angle between $\overrightarrow{AB}$ and $\overrightarrow{u}$, so we have 
$<B-A |\overrightarrow{u}> = \|\overrightarrow{AB}\| \cdot \cos{\theta}$, so we deduce that we
have 4 solutions (4 avalaible tangents) described by :

$$
\left\{ \begin{array}{ccl}
\cos{\theta} & = & \frac{r_A - \epsilon_1 \cdot r_B}{ \|\overrightarrow{AB}\| }, \\
\sin{\theta} & = & \epsilon_2 \cdot \sqrt{1 - \cos^2{\theta}},
\end{array}
\right.
$$

where $\epsilon_2 = \pm 1$.

If we denote by $\overrightarrow{x}$ the normal vector of $\overrightarrow{AB}$ and by $\overrightarrow{y}$ the orthonormal vector of $\overrightarrow{AB}$ we finally have :

$$
\overrightarrow{u} = \cos{\theta} \cdot \overrightarrow{x} + \sin{\theta} \cdot \overrightarrow{y} 
$$

where 
$\overrightarrow{x} = \frac{ \overrightarrow{AB}}{\|AB\|}$ and 
$\overrightarrow{y} = \left( -x[1], \atop x[0]\right)$.

** Incircle of a cone

Let $A$, $B$ and $C$ be three points.
Let $\widehat{ACB}$ be the cone whose vertex is $C$ and the lines are $(A,C)$ and $(B,C)$.

Let $\mathcal{C}$ be the incircle of the cone $\widehat{ACB}$.
Let $R$ be the radius of the circle. We want to compute the center $M$ of 
that circle.

Let $\overrightarrow{u} = \frac{ \overrightarrow{CA} }{ \| \overrightarrow{CA} \|}$ and
$\overrightarrow{v} = \frac{ \overrightarrow{CB} }{ \| \overrightarrow{CB} \|}$.

Then, if $\mathcal{C}$ is the incircle of $\widehat{ACB}$, then

$$
\left\{ \begin{array}{l}
\overrightarrow{u} \land \overrightarrow{CM} = \text{signe}( \overrightarrow{u} \land \overrightarrow{v} ) \cdot R \\
\overrightarrow{CM} \land \overrightarrow{v} = \text{signe}( \overrightarrow{u} \land \overrightarrow{v} ) \cdot R
\end{array}
\right.
$$

and so,

$$
\left\{ \begin{array}{l}
\overrightarrow{u} \land M = \text{signe}( \overrightarrow{u} \land \overrightarrow{v} ) \cdot R + \overrightarrow{u} \land C \\
M \land \overrightarrow{v} = \text{signe}( \overrightarrow{u} \land \overrightarrow{v} ) \cdot R + C \land \overrightarrow{v}
\end{array}
\right.
$$

where $\overrightarrow{u} \land M = u_x \cdot M_y - u_y \cdot M_x$ and 
$M \land \overrightarrow{v} = M_x \cdot v_y - M_y \cdot v_x$.

So we obtain,

$$
\left( \begin{array}{cc}
-u_y &  u_x \\
 v_y & -v_x
\end{array}
\right)
\cdot
\left( \begin{array}{c}
M_x \\
M_y
\end{array}
\right)
=
\left( \begin{array}{c}
\text{signe}( \overrightarrow{u} \land \overrightarrow{v} ) \cdot R + \overrightarrow{u} \land C \\
\text{signe}( \overrightarrow{u} \land \overrightarrow{v} ) \cdot R + C \land \overrightarrow{v}
\end{array}
\right)
$$

If we solve the equation, we obtain,

$$
\left( \begin{array}{c}
M_x \\
M_y
\end{array}
\right)
=
\left( \begin{array}{cc}
-u_y &  u_x \\
 v_y & -v_x
\end{array}
\right)^{-1}
\cdot
\left( \begin{array}{c}
\text{signe}( \overrightarrow{u} \land \overrightarrow{v} ) \cdot R + \overrightarrow{u} \land C \\
\text{signe}( \overrightarrow{u} \land \overrightarrow{v} ) \cdot R + C \land \overrightarrow{v}
\end{array}
\right)
$$

and so,

$$
\left( \begin{array}{c}
M_x \\
M_y
\end{array}
\right)
=
\frac{-1}{\overrightarrow{u} \land \overrightarrow{v}}
\left( \begin{array}{cc}
-v_x & -u_x \\
-v_y & -u_y
\end{array}
\right)
\cdot
\left( \begin{array}{c}
\text{signe}( \overrightarrow{u} \land \overrightarrow{v} ) \cdot R + \overrightarrow{u} \land C \\
\text{signe}( \overrightarrow{u} \land \overrightarrow{v} ) \cdot R + C \land \overrightarrow{v}
\end{array}
\right)
$$

and finally,

$$
\left( \begin{array}{c}
M_x \\
M_y
\end{array}
\right)
=
\frac{1}{\overrightarrow{u} \land \overrightarrow{v}}
\left( \begin{array}{cc}
v_x & u_x \\
v_y & u_y
\end{array}
\right)
\cdot
\left( \begin{array}{c}
\text{signe}( \overrightarrow{u} \land \overrightarrow{v} ) \cdot R + \overrightarrow{u} \land C \\
\text{signe}( \overrightarrow{u} \land \overrightarrow{v} ) \cdot R + C \land \overrightarrow{v}
\end{array}
\right)
$$

and finally,

$$
M =
\frac{1}{\overrightarrow{u} \land \overrightarrow{v}}
\cdot \left(
\text{signe}( \overrightarrow{u} \land \overrightarrow{v} ) \cdot R \cdot (\overrightarrow{u}+\overrightarrow{v}) +
( \overrightarrow{u} \land C ) \cdot \overrightarrow{v} + 
( C \land \overrightarrow{v} ) \cdot \overrightarrow{u}
\right).
$$
